target "NetworkService" do
use_frameworks!
pod 'RxSwift',    '~> 2.0'
pod 'RxCocoa'
platform :ios, '8.0'
use_frameworks!
pod 'Alamofire', '~> 3.0'



use_frameworks!
pod ‘Argo’, ‘2.2.0’ 
pod 'Runes'
pod 'Curry'
end